eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret: UGFWnRtZYFVPmSsXSBsv6Cqsf2zUONQ9dqLiUZGbk5wj1QUeOwp4NqQDMf7EmCp
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8765
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
  
